# Generated by Django 4.1.4 on 2022-12-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('DateTime', models.DateTimeField()),
                ('Travel_Medium', models.CharField(choices=[('bus', 'BUS'), ('car', 'CAR'), ('train', 'TRAIN')], max_length=20)),
                ('Asset_Quantity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('DateTime', models.DateTimeField()),
                ('No_Of_Assets', models.IntegerField(default=0)),
                ('Asset_Type', models.CharField(choices=[('laptop', 'LAPTOP'), ('travel_bag', 'TRAVEL_BAG'), ('package', 'PACKAGE')], max_length=20)),
                ('Asset_Sensitivity', models.CharField(choices=[('highly_sensitive', 'HIGHLY_SENSITIVE'), ('sensitive', 'SENSITIVE'), ('normal', 'NORMAL')], max_length=20)),
                ('Whom_To_Deliver', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
