# Generated by Django 4.1.4 on 2022-12-29 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestermodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 32, 47, 713958)),
        ),
        migrations.AlterField(
            model_name='ridermodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 32, 47, 698331)),
        ),
    ]
