# Generated by Django 4.1.4 on 2022-12-29 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_requestermodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestermodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 36, 44, 35254)),
        ),
        migrations.AlterField(
            model_name='ridermodel',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 36, 44, 35254)),
        ),
    ]
